version: '3.8'

services:
  empiriabms:
    image: empiriabms
    build:
      context: .
      dockerfile: EmpiriaBMS.Front/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - empiriabms_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "-Plata123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - empiriabms_network

volumes:
  db_data:

networks:
  empiriabms_network:
    driver: bridge
