// <auto-generated />
using System;
using EmpiriaBMS.EF.CLI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpiriaBMS.EF.CLI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240217200245_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpiriaBMS.Models.Models.ProjectEmployee", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProjectEmployee");

                    b.HasData(
                        new
                        {
                            ProjectId = 245740554,
                            EmployeeId = 209685584,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(224),
                            Id = 713577259,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(225)
                        },
                        new
                        {
                            ProjectId = 591804363,
                            EmployeeId = 810188773,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(554),
                            Id = 200938569,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(555)
                        },
                        new
                        {
                            ProjectId = 981541842,
                            EmployeeId = 216536264,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(856),
                            Id = 742539684,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(857)
                        },
                        new
                        {
                            ProjectId = 539171849,
                            EmployeeId = 871907095,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1077),
                            Id = 650076392,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1078)
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 545463596,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9812),
                            Description = "Test Description Employee 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Employee_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9813),
                            Phone1 = "6949277782"
                        },
                        new
                        {
                            Id = 635611476,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9957),
                            Description = "Test Description Client 0",
                            Email = "alexpl_0@gmail.com",
                            FirstName = "Platanios_Customer_0",
                            LastName = "Alexandros_0",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9958),
                            Phone1 = "6949277780",
                            ProjectId = 214971534
                        },
                        new
                        {
                            Id = 209685584,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(178),
                            Description = "Test Description Employee 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Employee_3",
                            Hours = 8.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(179),
                            Phone1 = "6949277783"
                        },
                        new
                        {
                            Id = 370977225,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(239),
                            Description = "Test Description Client 1",
                            Email = "alexpl_1@gmail.com",
                            FirstName = "Platanios_Customer_1",
                            LastName = "Alexandros_1",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(240),
                            Phone1 = "6949277781",
                            ProjectId = 245740554
                        },
                        new
                        {
                            Id = 581388523,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(294),
                            Description = "Test Description Employee 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Employee_4",
                            Hours = 16.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(296),
                            Phone1 = "6949277784"
                        },
                        new
                        {
                            Id = 626186467,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(376),
                            Description = "Test Description Client 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Customer_2",
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(378),
                            Phone1 = "6949277782",
                            ProjectId = 183486314
                        },
                        new
                        {
                            Id = 810188773,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(483),
                            Description = "Test Description Employee 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Employee_5",
                            Hours = 24.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(485),
                            Phone1 = "6949277785"
                        },
                        new
                        {
                            Id = 632786163,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(577),
                            Description = "Test Description Client 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Customer_3",
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(579),
                            Phone1 = "6949277783",
                            ProjectId = 591804363
                        },
                        new
                        {
                            Id = 162535765,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(655),
                            Description = "Test Description Employee 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Employee_6",
                            Hours = 32.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(657),
                            Phone1 = "6949277786"
                        },
                        new
                        {
                            Id = 174641641,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(735),
                            Description = "Test Description Client 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Customer_4",
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(736),
                            Phone1 = "6949277784",
                            ProjectId = 899861806
                        },
                        new
                        {
                            Id = 216536264,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(782),
                            Description = "Test Description Employee 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Employee_7",
                            Hours = 40.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(783),
                            Phone1 = "6949277787"
                        },
                        new
                        {
                            Id = 796396219,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(869),
                            Description = "Test Description Client 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Customer_5",
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(870),
                            Phone1 = "6949277785",
                            ProjectId = 981541842
                        },
                        new
                        {
                            Id = 422057560,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(926),
                            Description = "Test Description Employee 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Employee_8",
                            Hours = 48.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(927),
                            Phone1 = "6949277788"
                        },
                        new
                        {
                            Id = 706495715,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(969),
                            Description = "Test Description Client 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Customer_6",
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(970),
                            Phone1 = "6949277786",
                            ProjectId = 782371811
                        },
                        new
                        {
                            Id = 871907095,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1033),
                            Description = "Test Description Employee 9",
                            Email = "alexpl_9@gmail.com",
                            FirstName = "Platanios_Employee_9",
                            Hours = 56.0,
                            LastName = "Alexandros_9",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1034),
                            Phone1 = "6949277789"
                        },
                        new
                        {
                            Id = 212523897,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1089),
                            Description = "Test Description Client 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Customer_7",
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1090),
                            Phone1 = "6949277787",
                            ProjectId = 539171849
                        },
                        new
                        {
                            Id = 774871803,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1162),
                            Description = "Test Description Employee 10",
                            Email = "alexpl_10@gmail.com",
                            FirstName = "Platanios_Employee_10",
                            Hours = 64.0,
                            LastName = "Alexandros_10",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1163),
                            Phone1 = "69492777810"
                        },
                        new
                        {
                            Id = 975062454,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1210),
                            Description = "Test Description Client 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Customer_8",
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1211),
                            Phone1 = "6949277788",
                            ProjectId = 622816112
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 545463596,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9882),
                            Id = 231522843,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9884)
                        },
                        new
                        {
                            UserId = 635611476,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9978),
                            Id = 178055352,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9979)
                        },
                        new
                        {
                            UserId = 209685584,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(195),
                            Id = 829346634,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(196)
                        },
                        new
                        {
                            UserId = 370977225,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(256),
                            Id = 308993223,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(257)
                        },
                        new
                        {
                            UserId = 581388523,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(324),
                            Id = 949783269,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(326)
                        },
                        new
                        {
                            UserId = 626186467,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(403),
                            Id = 671797344,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(404)
                        },
                        new
                        {
                            UserId = 810188773,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(509),
                            Id = 865640892,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(511)
                        },
                        new
                        {
                            UserId = 632786163,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(604),
                            Id = 634584128,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(606)
                        },
                        new
                        {
                            UserId = 162535765,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(704),
                            Id = 663874279,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(705)
                        },
                        new
                        {
                            UserId = 174641641,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(752),
                            Id = 684680620,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(753)
                        },
                        new
                        {
                            UserId = 216536264,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(798),
                            Id = 609774229,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(799)
                        },
                        new
                        {
                            UserId = 796396219,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(896),
                            Id = 617222020,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(897)
                        },
                        new
                        {
                            UserId = 422057560,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(941),
                            Id = 160835749,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(942)
                        },
                        new
                        {
                            UserId = 706495715,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1004),
                            Id = 609291683,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1005)
                        },
                        new
                        {
                            UserId = 871907095,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1049),
                            Id = 540735491,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1050)
                        },
                        new
                        {
                            UserId = 212523897,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1104),
                            Id = 416040976,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1105)
                        },
                        new
                        {
                            UserId = 774871803,
                            RoleId = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1181),
                            Id = 304941550,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1182)
                        },
                        new
                        {
                            UserId = 975062454,
                            RoleId = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1226),
                            Id = 773212170,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1227)
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fee")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 937602094,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9993),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9995),
                            Fee = 3001.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9994),
                            Mark = "Signature 142340",
                            Number = 28356,
                            ProjectId = 214971534,
                            Total = 0.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 938775746,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(269),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(271),
                            Fee = 3010.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(270),
                            Mark = "Signature 142346",
                            Number = 89337,
                            ProjectId = 245740554,
                            Total = 1.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 689629364,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(425),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(428),
                            Fee = 3100.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(426),
                            Mark = "Signature 1423412",
                            Number = 86488,
                            ProjectId = 183486314,
                            Total = 2.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 773848234,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(628),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(632),
                            Fee = 4000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(630),
                            Mark = "Signature 1423412",
                            Number = 51338,
                            ProjectId = 591804363,
                            Total = 3.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 589933358,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(765),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(767),
                            Fee = 13000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(766),
                            Mark = "Signature 1423420",
                            Number = 51714,
                            ProjectId = 899861806,
                            Total = 4.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 571354772,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(909),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(911),
                            Fee = 103000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(910),
                            Mark = "Signature 1423430",
                            Number = 62926,
                            ProjectId = 981541842,
                            Total = 5.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 567260722,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1017),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1019),
                            Fee = 1003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1018),
                            Mark = "Signature 142346",
                            Number = 40086,
                            ProjectId = 782371811,
                            Total = 6.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 943764857,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1146),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1149),
                            Fee = 10003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1147),
                            Mark = "Signature 1423421",
                            Number = 45778,
                            ProjectId = 539171849,
                            Total = 7.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 406827934,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1239),
                            Date = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1241),
                            Fee = 100003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1240),
                            Mark = "Signature 142348",
                            Number = 20621,
                            ProjectId = 622816112,
                            Total = 8.0,
                            Vat = 24.0
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalculationDaly")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Completed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DayCost")
                        .HasColumnType("float");

                    b.Property<int?>("DaysUntilPayment")
                        .HasColumnType("int");

                    b.Property<int?>("DelayInPayment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drawing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DurationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaidFee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDetailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PendingPayments")
                        .HasColumnType("float");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 214971534,
                            Bank = "ALPHA",
                            CalculationDaly = 0,
                            Code = "D-22-160",
                            Completed = 0,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9895),
                            DayCost = 5.0,
                            DaysUntilPayment = -51,
                            DelayInPayment = 3,
                            Description = "Test Description Project_0",
                            Drawing = "KL-0",
                            DurationDate = new DateTime(2024, 4, 7, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9895),
                            EstPaymentDate = new DateTime(2024, 4, 7, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9895),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9895),
                            ManHours = 0,
                            Name = "Project_0",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 8, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9895),
                            PaymentDetailes = "Payment Detailes For Project_0",
                            PendingPayments = 0.0,
                            PlanType = 1,
                            WorkingDays = 200
                        },
                        new
                        {
                            Id = 245740554,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-161",
                            Completed = 10,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(203),
                            DayCost = 6.0,
                            DaysUntilPayment = -54,
                            DelayInPayment = 8,
                            Description = "Test Description Project_4",
                            Drawing = "KL-1",
                            DurationDate = new DateTime(2024, 4, 10, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(203),
                            EstPaymentDate = new DateTime(2024, 4, 9, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(203),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(203),
                            ManHours = 4,
                            Name = "Project_1",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 11, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(203),
                            PaymentDetailes = "Payment Detailes For Project_1",
                            PendingPayments = 1.0,
                            PlanType = 0,
                            WorkingDays = 203
                        },
                        new
                        {
                            Id = 183486314,
                            Bank = "ALPHA",
                            CalculationDaly = 2,
                            Code = "D-22-162",
                            Completed = 20,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(343),
                            DayCost = 7.0,
                            DaysUntilPayment = -57,
                            DelayInPayment = 13,
                            Description = "Test Description Project_8",
                            Drawing = "KL-2",
                            DurationDate = new DateTime(2024, 4, 13, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(343),
                            EstPaymentDate = new DateTime(2024, 4, 11, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(343),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(343),
                            ManHours = 8,
                            Name = "Project_2",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 14, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(343),
                            PaymentDetailes = "Payment Detailes For Project_8",
                            PendingPayments = 2.0,
                            PlanType = 1,
                            WorkingDays = 206
                        },
                        new
                        {
                            Id = 591804363,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 3,
                            Code = "D-22-163",
                            Completed = 30,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(523),
                            DayCost = 8.0,
                            DaysUntilPayment = -60,
                            DelayInPayment = 18,
                            Description = "Test Description Project_18",
                            Drawing = "KL-3",
                            DurationDate = new DateTime(2024, 4, 16, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(523),
                            EstPaymentDate = new DateTime(2024, 4, 13, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(523),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(523),
                            ManHours = 12,
                            Name = "Project_3",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(523),
                            PaymentDetailes = "Payment Detailes For Project_3",
                            PendingPayments = 3.0,
                            PlanType = 0,
                            WorkingDays = 209
                        },
                        new
                        {
                            Id = 899861806,
                            Bank = "ALPHA",
                            CalculationDaly = 4,
                            Code = "D-22-164",
                            Completed = 40,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(713),
                            DayCost = 9.0,
                            DaysUntilPayment = -63,
                            DelayInPayment = 23,
                            Description = "Test Description Project_16",
                            Drawing = "KL-4",
                            DurationDate = new DateTime(2024, 4, 19, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(713),
                            EstPaymentDate = new DateTime(2024, 4, 15, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(713),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(713),
                            ManHours = 16,
                            Name = "Project_4",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 20, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(713),
                            PaymentDetailes = "Payment Detailes For Project_20",
                            PendingPayments = 4.0,
                            PlanType = 1,
                            WorkingDays = 212
                        },
                        new
                        {
                            Id = 981541842,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-165",
                            Completed = 50,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(806),
                            DayCost = 10.0,
                            DaysUntilPayment = -66,
                            DelayInPayment = 28,
                            Description = "Test Description Project_30",
                            Drawing = "KL-5",
                            DurationDate = new DateTime(2024, 4, 22, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(806),
                            EstPaymentDate = new DateTime(2024, 4, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(806),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(806),
                            ManHours = 20,
                            Name = "Project_5",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 23, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(806),
                            PaymentDetailes = "Payment Detailes For Project_10",
                            PendingPayments = 5.0,
                            PlanType = 0,
                            WorkingDays = 215
                        },
                        new
                        {
                            Id = 782371811,
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-166",
                            Completed = 60,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(948),
                            DayCost = 11.0,
                            DaysUntilPayment = -69,
                            DelayInPayment = 33,
                            Description = "Test Description Project_24",
                            Drawing = "KL-6",
                            DurationDate = new DateTime(2024, 4, 25, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(948),
                            EstPaymentDate = new DateTime(2024, 4, 19, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(948),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(948),
                            ManHours = 24,
                            Name = "Project_6",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 26, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(948),
                            PaymentDetailes = "Payment Detailes For Project_12",
                            PendingPayments = 6.0,
                            PlanType = 1,
                            WorkingDays = 218
                        },
                        new
                        {
                            Id = 539171849,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-167",
                            Completed = 70,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1056),
                            DayCost = 12.0,
                            DaysUntilPayment = -72,
                            DelayInPayment = 38,
                            Description = "Test Description Project_21",
                            Drawing = "KL-7",
                            DurationDate = new DateTime(2024, 4, 28, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1056),
                            EstPaymentDate = new DateTime(2024, 4, 21, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1056),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1056),
                            ManHours = 28,
                            Name = "Project_7",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 29, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1056),
                            PaymentDetailes = "Payment Detailes For Project_35",
                            PendingPayments = 7.0,
                            PlanType = 0,
                            WorkingDays = 221
                        },
                        new
                        {
                            Id = 622816112,
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-168",
                            Completed = 80,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1190),
                            DayCost = 13.0,
                            DaysUntilPayment = -75,
                            DelayInPayment = 43,
                            Description = "Test Description Project_40",
                            Drawing = "KL-8",
                            DurationDate = new DateTime(2024, 5, 1, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1190),
                            EstPaymentDate = new DateTime(2024, 4, 23, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1190),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1190),
                            ManHours = 32,
                            Name = "Project_8",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 5, 2, 22, 2, 44, 783, DateTimeKind.Local).AddTicks(1190),
                            PaymentDetailes = "Payment Detailes For Project_16",
                            PendingPayments = 8.0,
                            PlanType = 1,
                            WorkingDays = 224
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 993533882,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9532),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9533),
                            Name = "Draftsmen"
                        },
                        new
                        {
                            Id = 846898163,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9541),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9542),
                            Name = "Engineers"
                        },
                        new
                        {
                            Id = 126868892,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9549),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9550),
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = 149098697,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9556),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9557),
                            Name = "COO"
                        },
                        new
                        {
                            Id = 943765270,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9563),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9564),
                            Name = "CTO"
                        },
                        new
                        {
                            Id = 860689953,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9570),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9571),
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 659989378,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9577),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9579),
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 530867923,
                            CreatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9584),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 22, 2, 44, 782, DateTimeKind.Local).AddTicks(9585),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.ProjectEmployee", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.User", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithOne("Customer")
                        .HasForeignKey("EmpiriaBMS.Models.Models.User", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaBMS.Models.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithOne("Invoice")
                        .HasForeignKey("EmpiriaMS.Models.Models.Invoice", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Navigation("ProjectEmployees");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("ProjectEmployees");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
