// <auto-generated />
using System;
using EmpiriaBMS.EF.CLI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpiriaBMS.EF.CLI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240218171915_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 234083652,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3588),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3589),
                            Name = "HVAC",
                            ProjectId = 715611564,
                            ProjectManagerId = 882449705
                        },
                        new
                        {
                            Id = 779139327,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3837),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3838),
                            Name = "ELEC",
                            ProjectId = 448570497,
                            ProjectManagerId = 194242074
                        },
                        new
                        {
                            Id = 358964667,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4054),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4056),
                            Name = "HVAC",
                            ProjectId = 750637520,
                            ProjectManagerId = 675538759
                        },
                        new
                        {
                            Id = 533024446,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4258),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4259),
                            Name = "ELEC",
                            ProjectId = 568325031,
                            ProjectManagerId = 917410259
                        },
                        new
                        {
                            Id = 701031954,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4467),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4468),
                            Name = "HVAC",
                            ProjectId = 493528078,
                            ProjectManagerId = 610998788
                        },
                        new
                        {
                            Id = 943404038,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4677),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4679),
                            Name = "ELEC",
                            ProjectId = 138668894,
                            ProjectManagerId = 338217635
                        },
                        new
                        {
                            Id = 821230563,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4880),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4881),
                            Name = "HVAC",
                            ProjectId = 463455076,
                            ProjectManagerId = 916865424
                        },
                        new
                        {
                            Id = 478720087,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5080),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5081),
                            Name = "ELEC",
                            ProjectId = 741153499,
                            ProjectManagerId = 401245866
                        },
                        new
                        {
                            Id = 903131476,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5294),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5295),
                            Name = "HVAC",
                            ProjectId = 238778979,
                            ProjectManagerId = 974098511
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.DisciplineEngineer", b =>
                {
                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<int>("EngineerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DisciplineId", "EngineerId");

                    b.HasIndex("EngineerId");

                    b.ToTable("DisciplinesEngineer");

                    b.HasData(
                        new
                        {
                            DisciplineId = 234083652,
                            EngineerId = 412468490,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3611),
                            Id = 744940138,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3613)
                        },
                        new
                        {
                            DisciplineId = 779139327,
                            EngineerId = 324614783,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3853),
                            Id = 790760092,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3854)
                        },
                        new
                        {
                            DisciplineId = 358964667,
                            EngineerId = 419958779,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4069),
                            Id = 417329750,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4071)
                        },
                        new
                        {
                            DisciplineId = 533024446,
                            EngineerId = 910425835,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4273),
                            Id = 982919869,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4274)
                        },
                        new
                        {
                            DisciplineId = 701031954,
                            EngineerId = 914472811,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4483),
                            Id = 618670582,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4484)
                        },
                        new
                        {
                            DisciplineId = 943404038,
                            EngineerId = 359402976,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4693),
                            Id = 369216567,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4694)
                        },
                        new
                        {
                            DisciplineId = 821230563,
                            EngineerId = 528471487,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4895),
                            Id = 156128836,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4896)
                        },
                        new
                        {
                            DisciplineId = 478720087,
                            EngineerId = 915910407,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5094),
                            Id = 741232764,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5096)
                        },
                        new
                        {
                            DisciplineId = 903131476,
                            EngineerId = 880646834,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5310),
                            Id = 506229822,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5311)
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Doc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ManHours")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Docs");

                    b.HasData(
                        new
                        {
                            Id = 342427123,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3662),
                            DisciplineId = 234083652,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3663),
                            ManHours = 0.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 696534768,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3884),
                            DisciplineId = 779139327,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3886),
                            ManHours = 1.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 995869077,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4100),
                            DisciplineId = 358964667,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4101),
                            ManHours = 6.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 659854728,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4307),
                            DisciplineId = 533024446,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4308),
                            ManHours = 3.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 929222132,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4516),
                            DisciplineId = 701031954,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4517),
                            ManHours = 16.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 902483839,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4724),
                            DisciplineId = 943404038,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4726),
                            ManHours = 5.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 686368075,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4927),
                            DisciplineId = 821230563,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4928),
                            ManHours = 12.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 144356692,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5125),
                            DisciplineId = 478720087,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5126),
                            ManHours = 21.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 316754440,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5343),
                            DisciplineId = 903131476,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5345),
                            ManHours = 24.0,
                            Name = "Draw_1"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ManHours")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Draws");

                    b.HasData(
                        new
                        {
                            Id = 810578028,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3637),
                            DisciplineId = 234083652,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3639),
                            ManHours = 0.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 473959995,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3867),
                            DisciplineId = 779139327,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3869),
                            ManHours = 3.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 939971878,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4084),
                            DisciplineId = 358964667,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4085),
                            ManHours = 2.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 721498226,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4288),
                            DisciplineId = 533024446,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4289),
                            ManHours = 12.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 499299728,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4499),
                            DisciplineId = 701031954,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4500),
                            ManHours = 16.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 973062275,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4708),
                            DisciplineId = 943404038,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4709),
                            ManHours = 15.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 405745297,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4911),
                            DisciplineId = 821230563,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4913),
                            ManHours = 12.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 486063370,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5109),
                            DisciplineId = 478720087,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5111),
                            ManHours = 14.0,
                            Name = "Draw_1"
                        },
                        new
                        {
                            Id = 288561714,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5326),
                            DisciplineId = 903131476,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5327),
                            ManHours = 24.0,
                            Name = "Draw_1"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 763211220,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3400),
                            Description = "Test Description Client 0",
                            Email = "alexpl_0@gmail.com",
                            FirstName = "Platanios_Customer_0",
                            LastName = "Alexandros_0",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3402),
                            Phone1 = "6949277780",
                            ProjectId = 715611564
                        },
                        new
                        {
                            Id = 882449705,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3506),
                            Description = "Test Description Employee 2",
                            Email = "alexpl_21@gmail.com",
                            FirstName = "Platanios_Employee_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3507),
                            Phone1 = "6949277782"
                        },
                        new
                        {
                            Id = 412468490,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3548),
                            Description = "Test Description Employee 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Employee_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3549),
                            Phone1 = "6949277782"
                        },
                        new
                        {
                            Id = 316004911,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3708),
                            Description = "Test Description Client 1",
                            Email = "alexpl_1@gmail.com",
                            FirstName = "Platanios_Customer_1",
                            LastName = "Alexandros_1",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3709),
                            Phone1 = "6949277781",
                            ProjectId = 448570497
                        },
                        new
                        {
                            Id = 194242074,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3764),
                            Description = "Test Description Employee 3",
                            Email = "alexpl_22@gmail.com",
                            FirstName = "Platanios_Employee_3",
                            Hours = 8.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3765),
                            Phone1 = "6949277783"
                        },
                        new
                        {
                            Id = 324614783,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3802),
                            Description = "Test Description Employee 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Employee_3",
                            Hours = 8.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3803),
                            Phone1 = "6949277783"
                        },
                        new
                        {
                            Id = 510991788,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3922),
                            Description = "Test Description Client 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Customer_2",
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3924),
                            Phone1 = "6949277782",
                            ProjectId = 750637520
                        },
                        new
                        {
                            Id = 675538759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3983),
                            Description = "Test Description Employee 4",
                            Email = "alexpl_23@gmail.com",
                            FirstName = "Platanios_Employee_4",
                            Hours = 16.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3984),
                            Phone1 = "6949277784"
                        },
                        new
                        {
                            Id = 419958779,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4018),
                            Description = "Test Description Employee 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Employee_4",
                            Hours = 16.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4019),
                            Phone1 = "6949277784"
                        },
                        new
                        {
                            Id = 731736439,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4136),
                            Description = "Test Description Client 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Customer_3",
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4137),
                            Phone1 = "6949277783",
                            ProjectId = 568325031
                        },
                        new
                        {
                            Id = 917410259,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4189),
                            Description = "Test Description Employee 5",
                            Email = "alexpl_24@gmail.com",
                            FirstName = "Platanios_Employee_5",
                            Hours = 24.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4190),
                            Phone1 = "6949277785"
                        },
                        new
                        {
                            Id = 910425835,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4224),
                            Description = "Test Description Employee 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Employee_5",
                            Hours = 24.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4226),
                            Phone1 = "6949277785"
                        },
                        new
                        {
                            Id = 921723374,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4344),
                            Description = "Test Description Client 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Customer_4",
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4346),
                            Phone1 = "6949277784",
                            ProjectId = 493528078
                        },
                        new
                        {
                            Id = 610998788,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4400),
                            Description = "Test Description Employee 6",
                            Email = "alexpl_25@gmail.com",
                            FirstName = "Platanios_Employee_6",
                            Hours = 32.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4401),
                            Phone1 = "6949277786"
                        },
                        new
                        {
                            Id = 914472811,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4434),
                            Description = "Test Description Employee 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Employee_6",
                            Hours = 32.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4435),
                            Phone1 = "6949277786"
                        },
                        new
                        {
                            Id = 679474340,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4553),
                            Description = "Test Description Client 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Customer_5",
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4555),
                            Phone1 = "6949277785",
                            ProjectId = 138668894
                        },
                        new
                        {
                            Id = 338217635,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4608),
                            Description = "Test Description Employee 7",
                            Email = "alexpl_26@gmail.com",
                            FirstName = "Platanios_Employee_7",
                            Hours = 40.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4610),
                            Phone1 = "6949277787"
                        },
                        new
                        {
                            Id = 359402976,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4644),
                            Description = "Test Description Employee 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Employee_7",
                            Hours = 40.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4645),
                            Phone1 = "6949277787"
                        },
                        new
                        {
                            Id = 137798425,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4760),
                            Description = "Test Description Client 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Customer_6",
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4761),
                            Phone1 = "6949277786",
                            ProjectId = 463455076
                        },
                        new
                        {
                            Id = 916865424,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4812),
                            Description = "Test Description Employee 8",
                            Email = "alexpl_27@gmail.com",
                            FirstName = "Platanios_Employee_8",
                            Hours = 48.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4813),
                            Phone1 = "6949277788"
                        },
                        new
                        {
                            Id = 528471487,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4845),
                            Description = "Test Description Employee 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Employee_8",
                            Hours = 48.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4847),
                            Phone1 = "6949277788"
                        },
                        new
                        {
                            Id = 690029598,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4962),
                            Description = "Test Description Client 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Customer_7",
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4963),
                            Phone1 = "6949277787",
                            ProjectId = 741153499
                        },
                        new
                        {
                            Id = 401245866,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5013),
                            Description = "Test Description Employee 9",
                            Email = "alexpl_28@gmail.com",
                            FirstName = "Platanios_Employee_9",
                            Hours = 56.0,
                            LastName = "Alexandros_9",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5015),
                            Phone1 = "6949277789"
                        },
                        new
                        {
                            Id = 915910407,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5047),
                            Description = "Test Description Employee 9",
                            Email = "alexpl_9@gmail.com",
                            FirstName = "Platanios_Employee_9",
                            Hours = 56.0,
                            LastName = "Alexandros_9",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5048),
                            Phone1 = "6949277789"
                        },
                        new
                        {
                            Id = 344697142,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5164),
                            Description = "Test Description Client 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Customer_8",
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5165),
                            Phone1 = "6949277788",
                            ProjectId = 238778979
                        },
                        new
                        {
                            Id = 974098511,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5223),
                            Description = "Test Description Employee 10",
                            Email = "alexpl_29@gmail.com",
                            FirstName = "Platanios_Employee_10",
                            Hours = 64.0,
                            LastName = "Alexandros_10",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5225),
                            Phone1 = "69492777810"
                        },
                        new
                        {
                            Id = 880646834,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5259),
                            Description = "Test Description Employee 10",
                            Email = "alexpl_10@gmail.com",
                            FirstName = "Platanios_Employee_10",
                            Hours = 64.0,
                            LastName = "Alexandros_10",
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5260),
                            Phone1 = "69492777810"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 763211220,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3450),
                            Id = 202334410,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3451)
                        },
                        new
                        {
                            UserId = 882449705,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3531),
                            Id = 496679428,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3533)
                        },
                        new
                        {
                            UserId = 412468490,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3571),
                            Id = 219679779,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3573)
                        },
                        new
                        {
                            UserId = 316004911,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3728),
                            Id = 284326286,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3730)
                        },
                        new
                        {
                            UserId = 194242074,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3785),
                            Id = 828573721,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3787)
                        },
                        new
                        {
                            UserId = 324614783,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3822),
                            Id = 499637115,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3823)
                        },
                        new
                        {
                            UserId = 510991788,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3941),
                            Id = 963567236,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3943)
                        },
                        new
                        {
                            UserId = 675538759,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4003),
                            Id = 876352471,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4004)
                        },
                        new
                        {
                            UserId = 419958779,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4038),
                            Id = 858802421,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4040)
                        },
                        new
                        {
                            UserId = 731736439,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4154),
                            Id = 376986600,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4155)
                        },
                        new
                        {
                            UserId = 917410259,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4209),
                            Id = 192231584,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4211)
                        },
                        new
                        {
                            UserId = 910425835,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4243),
                            Id = 678773179,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4245)
                        },
                        new
                        {
                            UserId = 921723374,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4364),
                            Id = 258060837,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4365)
                        },
                        new
                        {
                            UserId = 610998788,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4419),
                            Id = 807446594,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4420)
                        },
                        new
                        {
                            UserId = 914472811,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4453),
                            Id = 352017936,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4454)
                        },
                        new
                        {
                            UserId = 679474340,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4572),
                            Id = 380975045,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4574)
                        },
                        new
                        {
                            UserId = 338217635,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4628),
                            Id = 151734635,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4629)
                        },
                        new
                        {
                            UserId = 359402976,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4663),
                            Id = 483643477,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4664)
                        },
                        new
                        {
                            UserId = 137798425,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4778),
                            Id = 752228537,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4780)
                        },
                        new
                        {
                            UserId = 916865424,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4830),
                            Id = 348962874,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4832)
                        },
                        new
                        {
                            UserId = 528471487,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4865),
                            Id = 580109641,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4866)
                        },
                        new
                        {
                            UserId = 690029598,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4980),
                            Id = 879443579,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4981)
                        },
                        new
                        {
                            UserId = 401245866,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5032),
                            Id = 482879901,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5033)
                        },
                        new
                        {
                            UserId = 915910407,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5065),
                            Id = 375827667,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5066)
                        },
                        new
                        {
                            UserId = 344697142,
                            RoleId = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5183),
                            Id = 564932544,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5184)
                        },
                        new
                        {
                            UserId = 974098511,
                            RoleId = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5244),
                            Id = 751496018,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5245)
                        },
                        new
                        {
                            UserId = 880646834,
                            RoleId = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5279),
                            Id = 820589978,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5281)
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fee")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 523792813,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3472),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3475),
                            Fee = 3001.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3473),
                            Mark = "Signature 142340",
                            Number = 84819,
                            ProjectId = 715611564,
                            Total = 0.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 557811801,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3743),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3746),
                            Fee = 3010.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3745),
                            Mark = "Signature 142346",
                            Number = 74922,
                            ProjectId = 448570497,
                            Total = 1.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 689389620,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3957),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3960),
                            Fee = 3100.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3958),
                            Mark = "Signature 142342",
                            Number = 27975,
                            ProjectId = 750637520,
                            Total = 2.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 403772250,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4169),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4171),
                            Fee = 4000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4170),
                            Mark = "Signature 1423415",
                            Number = 10860,
                            ProjectId = 568325031,
                            Total = 3.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 513908488,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4379),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4382),
                            Fee = 13000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4380),
                            Mark = "Signature 142344",
                            Number = 65582,
                            ProjectId = 493528078,
                            Total = 4.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 438256150,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4588),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4590),
                            Fee = 103000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4589),
                            Mark = "Signature 142345",
                            Number = 47996,
                            ProjectId = 138668894,
                            Total = 5.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 518694235,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4793),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4796),
                            Fee = 1003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4794),
                            Mark = "Signature 1423418",
                            Number = 67014,
                            ProjectId = 463455076,
                            Total = 6.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = 629318984,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4995),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4998),
                            Fee = 10003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4996),
                            Mark = "Signature 1423414",
                            Number = 66763,
                            ProjectId = 741153499,
                            Total = 7.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = 658452035,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5198),
                            Date = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5200),
                            Fee = 100003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5199),
                            Mark = "Signature 1423416",
                            Number = 69593,
                            ProjectId = 238778979,
                            Total = 8.0,
                            Vat = 24.0
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalculationDaly")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Completed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DayCost")
                        .HasColumnType("float");

                    b.Property<int?>("DaysUntilPayment")
                        .HasColumnType("int");

                    b.Property<int?>("DelayInPayment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drawing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DurationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaidFee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDetailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PendingPayments")
                        .HasColumnType("float");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 715611564,
                            Bank = "ALPHA",
                            CalculationDaly = 0,
                            Code = "D-22-160",
                            Completed = 0,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3347),
                            DayCost = 5.0,
                            DaysUntilPayment = -51,
                            DelayInPayment = 3,
                            Description = "Test Description Project_0",
                            Drawing = "KL-0",
                            DurationDate = new DateTime(2024, 4, 8, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3347),
                            EstPaymentDate = new DateTime(2024, 4, 8, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3347),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3347),
                            ManHours = 0,
                            Name = "Project_0",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 9, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3347),
                            PaymentDetailes = "Payment Detailes For Project_0",
                            PendingPayments = 0.0,
                            PlanType = 1,
                            WorkingDays = 200
                        },
                        new
                        {
                            Id = 448570497,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-161",
                            Completed = 10,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3680),
                            DayCost = 6.0,
                            DaysUntilPayment = -54,
                            DelayInPayment = 8,
                            Description = "Test Description Project_2",
                            Drawing = "KL-1",
                            DurationDate = new DateTime(2024, 4, 11, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3680),
                            EstPaymentDate = new DateTime(2024, 4, 10, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3680),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3680),
                            ManHours = 4,
                            Name = "Project_1",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 12, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3680),
                            PaymentDetailes = "Payment Detailes For Project_6",
                            PendingPayments = 1.0,
                            PlanType = 0,
                            WorkingDays = 203
                        },
                        new
                        {
                            Id = 750637520,
                            Bank = "ALPHA",
                            CalculationDaly = 2,
                            Code = "D-22-162",
                            Completed = 20,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3897),
                            DayCost = 7.0,
                            DaysUntilPayment = -57,
                            DelayInPayment = 13,
                            Description = "Test Description Project_4",
                            Drawing = "KL-2",
                            DurationDate = new DateTime(2024, 4, 14, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3897),
                            EstPaymentDate = new DateTime(2024, 4, 12, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3897),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3897),
                            ManHours = 8,
                            Name = "Project_2",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 15, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3897),
                            PaymentDetailes = "Payment Detailes For Project_10",
                            PendingPayments = 2.0,
                            PlanType = 1,
                            WorkingDays = 206
                        },
                        new
                        {
                            Id = 568325031,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 3,
                            Code = "D-22-163",
                            Completed = 30,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4111),
                            DayCost = 8.0,
                            DaysUntilPayment = -60,
                            DelayInPayment = 18,
                            Description = "Test Description Project_3",
                            Drawing = "KL-3",
                            DurationDate = new DateTime(2024, 4, 17, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4111),
                            EstPaymentDate = new DateTime(2024, 4, 14, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4111),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4111),
                            ManHours = 12,
                            Name = "Project_3",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4111),
                            PaymentDetailes = "Payment Detailes For Project_15",
                            PendingPayments = 3.0,
                            PlanType = 0,
                            WorkingDays = 209
                        },
                        new
                        {
                            Id = 493528078,
                            Bank = "ALPHA",
                            CalculationDaly = 4,
                            Code = "D-22-164",
                            Completed = 40,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4318),
                            DayCost = 9.0,
                            DaysUntilPayment = -63,
                            DelayInPayment = 23,
                            Description = "Test Description Project_12",
                            Drawing = "KL-4",
                            DurationDate = new DateTime(2024, 4, 20, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4318),
                            EstPaymentDate = new DateTime(2024, 4, 16, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4318),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4318),
                            ManHours = 16,
                            Name = "Project_4",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 21, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4318),
                            PaymentDetailes = "Payment Detailes For Project_12",
                            PendingPayments = 4.0,
                            PlanType = 1,
                            WorkingDays = 212
                        },
                        new
                        {
                            Id = 138668894,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-165",
                            Completed = 50,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4528),
                            DayCost = 10.0,
                            DaysUntilPayment = -66,
                            DelayInPayment = 28,
                            Description = "Test Description Project_20",
                            Drawing = "KL-5",
                            DurationDate = new DateTime(2024, 4, 23, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4528),
                            EstPaymentDate = new DateTime(2024, 4, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4528),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4528),
                            ManHours = 20,
                            Name = "Project_5",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 24, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4528),
                            PaymentDetailes = "Payment Detailes For Project_10",
                            PendingPayments = 5.0,
                            PlanType = 0,
                            WorkingDays = 215
                        },
                        new
                        {
                            Id = 463455076,
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-166",
                            Completed = 60,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4736),
                            DayCost = 11.0,
                            DaysUntilPayment = -69,
                            DelayInPayment = 33,
                            Description = "Test Description Project_36",
                            Drawing = "KL-6",
                            DurationDate = new DateTime(2024, 4, 26, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4736),
                            EstPaymentDate = new DateTime(2024, 4, 20, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4736),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4736),
                            ManHours = 24,
                            Name = "Project_6",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 27, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4736),
                            PaymentDetailes = "Payment Detailes For Project_18",
                            PendingPayments = 6.0,
                            PlanType = 1,
                            WorkingDays = 218
                        },
                        new
                        {
                            Id = 741153499,
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-167",
                            Completed = 70,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4938),
                            DayCost = 12.0,
                            DaysUntilPayment = -72,
                            DelayInPayment = 38,
                            Description = "Test Description Project_14",
                            Drawing = "KL-7",
                            DurationDate = new DateTime(2024, 4, 29, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4938),
                            EstPaymentDate = new DateTime(2024, 4, 22, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4938),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4938),
                            ManHours = 28,
                            Name = "Project_7",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 30, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(4938),
                            PaymentDetailes = "Payment Detailes For Project_14",
                            PendingPayments = 7.0,
                            PlanType = 0,
                            WorkingDays = 221
                        },
                        new
                        {
                            Id = 238778979,
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-168",
                            Completed = 80,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5137),
                            DayCost = 13.0,
                            DaysUntilPayment = -75,
                            DelayInPayment = 43,
                            Description = "Test Description Project_32",
                            Drawing = "KL-8",
                            DurationDate = new DateTime(2024, 5, 2, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5137),
                            EstPaymentDate = new DateTime(2024, 4, 24, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5137),
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5137),
                            ManHours = 32,
                            Name = "Project_8",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 5, 3, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(5137),
                            PaymentDetailes = "Payment Detailes For Project_8",
                            PendingPayments = 8.0,
                            PlanType = 1,
                            WorkingDays = 224
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 500840904,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3163),
                            IsEmployee = true,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3165),
                            Name = "Draftsmen"
                        },
                        new
                        {
                            Id = 783469795,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3175),
                            IsEmployee = true,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3176),
                            Name = "Engineers"
                        },
                        new
                        {
                            Id = 185205596,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3184),
                            IsEmployee = true,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3185),
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = 477335804,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3193),
                            IsEmployee = true,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3194),
                            Name = "COO"
                        },
                        new
                        {
                            Id = 580514221,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3202),
                            IsEmployee = true,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3204),
                            Name = "CTO"
                        },
                        new
                        {
                            Id = 982815245,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3211),
                            IsEmployee = true,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3212),
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 250469691,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3219),
                            IsEmployee = false,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3221),
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 646599759,
                            CreatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3228),
                            IsEmployee = false,
                            LastUpdatedDate = new DateTime(2024, 2, 18, 19, 19, 15, 415, DateTimeKind.Local).AddTicks(3229),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Discipline", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithMany("Disciplines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaBMS.Models.Models.User", "ProjectManager")
                        .WithMany("Disciplines")
                        .HasForeignKey("ProjectManagerId");

                    b.Navigation("Project");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.DisciplineEngineer", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.Discipline", "Discipline")
                        .WithMany("DisciplineEngineers")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaBMS.Models.Models.User", "Engineer")
                        .WithMany("DisciplineEngineers")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Doc", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.Discipline", "Discipline")
                        .WithMany("Docs")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Draw", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.Discipline", "Discipline")
                        .WithMany("Draws")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.Discipline", null)
                        .WithMany("Engineers")
                        .HasForeignKey("DisciplineId");

                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithOne("Customer")
                        .HasForeignKey("EmpiriaBMS.Models.Models.User", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaBMS.Models.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithOne("Invoice")
                        .HasForeignKey("EmpiriaMS.Models.Models.Invoice", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.Discipline", b =>
                {
                    b.Navigation("DisciplineEngineers");

                    b.Navigation("Docs");

                    b.Navigation("Draws");

                    b.Navigation("Engineers");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Navigation("DisciplineEngineers");

                    b.Navigation("Disciplines");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Disciplines");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
