// <auto-generated />
using System;
using EmpiriaBMS.EF.CLI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpiriaBMS.EF.CLI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240217190453_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpiriaBMS.Models.Models.ProjectEmployee", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProjectEmployee");

                    b.HasData(
                        new
                        {
                            ProjectId = "98860854fd7e41f68414910c2161eb494",
                            EmployeeId = "88b2602f3bd046588cf9a857e6414ef13",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3176),
                            Id = "daee682852864407a40b8ff2122bd1c44",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3177)
                        },
                        new
                        {
                            ProjectId = "37963bd92712463f8f9dd98060670f2e18",
                            EmployeeId = "ebe452ef6ae045b7879b9d1d53f77b623",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3480),
                            Id = "e3842849053240cd85995968da98b5c418",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3482)
                        },
                        new
                        {
                            ProjectId = "2f50bc95eefe4ef7a5010cb1bb7280985",
                            EmployeeId = "f359b26ceefe43caaa39235159c314b715",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3896),
                            Id = "7f86bbc9347a4fe0bce96f10b2e62cdb30",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3897)
                        },
                        new
                        {
                            ProjectId = "19a7ceeac3a64225b523f9fa4704020442",
                            EmployeeId = "3eea506610c04b65b98d13b664bf000a42",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4211),
                            Id = "09642be95ab5484a9fa95c79bde319e842",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4213)
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "7667ea76f25d4c75886164c475954eeb0",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2870),
                            Description = "Test Description Employee 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Employee_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2871),
                            Phone1 = "6949277782"
                        },
                        new
                        {
                            Id = "ae3bd06b892e45d490e2116caaefad800",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3024),
                            Description = "Test Description Client 0",
                            Email = "alexpl_0@gmail.com",
                            FirstName = "Platanios_Customer_0",
                            LastName = "Alexandros_0",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3026),
                            Phone1 = "6949277780",
                            ProjectId = "1979eb652f5942b9a626dc262f57802e0"
                        },
                        new
                        {
                            Id = "88b2602f3bd046588cf9a857e6414ef13",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3114),
                            Description = "Test Description Employee 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Employee_3",
                            Hours = 8.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3115),
                            Phone1 = "6949277783"
                        },
                        new
                        {
                            Id = "815a23939c484056b5a6295145316a072",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3199),
                            Description = "Test Description Client 1",
                            Email = "alexpl_1@gmail.com",
                            FirstName = "Platanios_Customer_1",
                            LastName = "Alexandros_1",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3201),
                            Phone1 = "6949277781",
                            ProjectId = "98860854fd7e41f68414910c2161eb494"
                        },
                        new
                        {
                            Id = "16be943f528a4e109841ba5413c47a5b6",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3261),
                            Description = "Test Description Employee 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Employee_4",
                            Hours = 16.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3262),
                            Phone1 = "6949277784"
                        },
                        new
                        {
                            Id = "c6735b200ee24c7d94ee5d334793ff0210",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3351),
                            Description = "Test Description Client 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Customer_2",
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3352),
                            Phone1 = "6949277782",
                            ProjectId = "d7a8dac9771649a69478180af68804698"
                        },
                        new
                        {
                            Id = "ebe452ef6ae045b7879b9d1d53f77b623",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3420),
                            Description = "Test Description Employee 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Employee_5",
                            Hours = 24.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3421),
                            Phone1 = "6949277785"
                        },
                        new
                        {
                            Id = "92d2e1d63a7e49a09506b744856a5add6",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3564),
                            Description = "Test Description Client 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Customer_3",
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3565),
                            Phone1 = "6949277783",
                            ProjectId = "37963bd92712463f8f9dd98060670f2e18"
                        },
                        new
                        {
                            Id = "d9c169d163124fe1a3fb5e442ef0c19120",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3657),
                            Description = "Test Description Employee 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Employee_6",
                            Hours = 32.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3658),
                            Phone1 = "6949277786"
                        },
                        new
                        {
                            Id = "ee1d258ecbaa4c29a44f28b08630d5574",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3741),
                            Description = "Test Description Client 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Customer_4",
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3743),
                            Phone1 = "6949277784",
                            ProjectId = "b407d0a5d297497392ddc24b0266a84512"
                        },
                        new
                        {
                            Id = "f359b26ceefe43caaa39235159c314b715",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3807),
                            Description = "Test Description Employee 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Employee_7",
                            Hours = 40.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3808),
                            Phone1 = "6949277787"
                        },
                        new
                        {
                            Id = "cd903da4c12c4cb89403faef19b4848b15",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3915),
                            Description = "Test Description Client 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Customer_5",
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3916),
                            Phone1 = "6949277785",
                            ProjectId = "2f50bc95eefe4ef7a5010cb1bb7280985"
                        },
                        new
                        {
                            Id = "a8ef4419c9e24024b2119ea91bd53b6718",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3990),
                            Description = "Test Description Employee 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Employee_8",
                            Hours = 48.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3991),
                            Phone1 = "6949277788"
                        },
                        new
                        {
                            Id = "4cde91b22c034bddb9359533995975f424",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4052),
                            Description = "Test Description Client 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Customer_6",
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4053),
                            Phone1 = "6949277786",
                            ProjectId = "092a7ad5c1af440d90e69a311afa6f9a36"
                        },
                        new
                        {
                            Id = "3eea506610c04b65b98d13b664bf000a42",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4125),
                            Description = "Test Description Employee 9",
                            Email = "alexpl_9@gmail.com",
                            FirstName = "Platanios_Employee_9",
                            Hours = 56.0,
                            LastName = "Alexandros_9",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4126),
                            Phone1 = "6949277789"
                        },
                        new
                        {
                            Id = "4594e791ff0d42c38a22bd622cb45bea42",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4230),
                            Description = "Test Description Client 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Customer_7",
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4231),
                            Phone1 = "6949277787",
                            ProjectId = "19a7ceeac3a64225b523f9fa4704020442"
                        },
                        new
                        {
                            Id = "ad75147f9a1f4ac998adf7b993bda1218",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4292),
                            Description = "Test Description Employee 10",
                            Email = "alexpl_10@gmail.com",
                            FirstName = "Platanios_Employee_10",
                            Hours = 64.0,
                            LastName = "Alexandros_10",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4293),
                            Phone1 = "69492777810"
                        },
                        new
                        {
                            Id = "be901d40ee554f5590c340b6a941779848",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4381),
                            Description = "Test Description Client 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Customer_8",
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4382),
                            Phone1 = "6949277788",
                            ProjectId = "c179b725625c4bcfb9413bcd0488244e32"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = "7667ea76f25d4c75886164c475954eeb0",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2938),
                            Id = "b75972b5a76944ce968d99ffd1de9c51",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2940)
                        },
                        new
                        {
                            UserId = "ae3bd06b892e45d490e2116caaefad800",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3051),
                            Id = "d46c867bc60d4611b809d07f7c9591da",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3052)
                        },
                        new
                        {
                            UserId = "88b2602f3bd046588cf9a857e6414ef13",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3135),
                            Id = "0b538be3b4714cf6a22e2903888556f5",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3136)
                        },
                        new
                        {
                            UserId = "815a23939c484056b5a6295145316a072",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3221),
                            Id = "8f1ae8886a4848b3887bc242d40dbf4f",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3222)
                        },
                        new
                        {
                            UserId = "16be943f528a4e109841ba5413c47a5b6",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3308),
                            Id = "019f2f33c7fb429ea3d74c76a55f389a",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3310)
                        },
                        new
                        {
                            UserId = "c6735b200ee24c7d94ee5d334793ff0210",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3373),
                            Id = "9165f247cbc14e72b8d0ca1f7bde839d",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3374)
                        },
                        new
                        {
                            UserId = "ebe452ef6ae045b7879b9d1d53f77b623",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3440),
                            Id = "1215c7f387144a689185c0ba15ffe8ec",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3441)
                        },
                        new
                        {
                            UserId = "92d2e1d63a7e49a09506b744856a5add6",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3586),
                            Id = "87db88bec61d48e3bdf1e291066392f7",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3588)
                        },
                        new
                        {
                            UserId = "d9c169d163124fe1a3fb5e442ef0c19120",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3700),
                            Id = "fe1b28f3acf44a449d6fb30580bdb9c7",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3701)
                        },
                        new
                        {
                            UserId = "ee1d258ecbaa4c29a44f28b08630d5574",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3764),
                            Id = "35b8b78f322d4311a3d193d079f5e8fe",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3765)
                        },
                        new
                        {
                            UserId = "f359b26ceefe43caaa39235159c314b715",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3828),
                            Id = "36fd5990df774744b697069786ffbb7e",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3829)
                        },
                        new
                        {
                            UserId = "cd903da4c12c4cb89403faef19b4848b15",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3947),
                            Id = "03a194bd08f54a1ba34cf1e7e3dcbe1d",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3948)
                        },
                        new
                        {
                            UserId = "a8ef4419c9e24024b2119ea91bd53b6718",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4010),
                            Id = "60335b34dce44537a61918a49c900ea3",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4012)
                        },
                        new
                        {
                            UserId = "4cde91b22c034bddb9359533995975f424",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4086),
                            Id = "2974538294274494830943c74ba1af62",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4087)
                        },
                        new
                        {
                            UserId = "3eea506610c04b65b98d13b664bf000a42",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4171),
                            Id = "e826095e953a4b3db7f7deaae7743f54",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4173)
                        },
                        new
                        {
                            UserId = "4594e791ff0d42c38a22bd622cb45bea42",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4252),
                            Id = "1f3af12a81b9407c833d0f964766c84c",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4253)
                        },
                        new
                        {
                            UserId = "ad75147f9a1f4ac998adf7b993bda1218",
                            RoleId = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4314),
                            Id = "7911d8d893274eab9f16f1bb725e9103",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4315)
                        },
                        new
                        {
                            UserId = "be901d40ee554f5590c340b6a941779848",
                            RoleId = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4402),
                            Id = "e34fafc76a2f4b269d6f248e9df5bd86",
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4403)
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fee")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = "c2d12651e71e4982b38da3717c3e08df0",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3071),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3073),
                            Fee = 3001.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3072),
                            Mark = "Signature 142340",
                            Number = 43370,
                            ProjectId = "1979eb652f5942b9a626dc262f57802e0",
                            Total = 0.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "4f2a19dc94ac48a08bd6630ffaf384f86",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3239),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3242),
                            Fee = 3010.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3241),
                            Mark = "Signature 142342",
                            Number = 57429,
                            ProjectId = "98860854fd7e41f68414910c2161eb494",
                            Total = 1.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "33f0bc7c6fe84042a4f6f033125fa7216",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3393),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3395),
                            Fee = 3100.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3394),
                            Mark = "Signature 1423410",
                            Number = 85252,
                            ProjectId = "d7a8dac9771649a69478180af68804698",
                            Total = 2.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "2f5fd977d79e4d59b84d82ea2d13b28d18",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3631),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3633),
                            Fee = 4000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3632),
                            Mark = "Signature 1423415",
                            Number = 43051,
                            ProjectId = "37963bd92712463f8f9dd98060670f2e18",
                            Total = 3.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "a8e09376b941439188308b539535b6f224",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3782),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3785),
                            Fee = 13000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3783),
                            Mark = "Signature 142344",
                            Number = 81926,
                            ProjectId = "b407d0a5d297497392ddc24b0266a84512",
                            Total = 4.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "4185612b79244b5f9d301c42fc249dfa30",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3967),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3969),
                            Fee = 103000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3968),
                            Mark = "Signature 142345",
                            Number = 36345,
                            ProjectId = "2f50bc95eefe4ef7a5010cb1bb7280985",
                            Total = 5.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "dc40c0dd386e4b7a8ce1298fb66fedb418",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4104),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4107),
                            Fee = 1003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4106),
                            Mark = "Signature 1423436",
                            Number = 28327,
                            ProjectId = "092a7ad5c1af440d90e69a311afa6f9a36",
                            Total = 6.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "50a9d4423bcf4aef8a501f90e520dff642",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4270),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4272),
                            Fee = 10003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4271),
                            Mark = "Signature 1423435",
                            Number = 55721,
                            ProjectId = "19a7ceeac3a64225b523f9fa4704020442",
                            Total = 7.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "2abf0a753b7741af9fb7f97eb121bd2248",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4420),
                            Date = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4422),
                            Fee = 100003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4421),
                            Mark = "Signature 142348",
                            Number = 13110,
                            ProjectId = "c179b725625c4bcfb9413bcd0488244e32",
                            Total = 8.0,
                            Vat = 24.0
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalculationDaly")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Completed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DayCost")
                        .HasColumnType("float");

                    b.Property<int?>("DaysUntilPayment")
                        .HasColumnType("int");

                    b.Property<int?>("DelayInPayment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drawing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DurationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaidFee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDetailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PendingPayments")
                        .HasColumnType("float");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "1979eb652f5942b9a626dc262f57802e0",
                            Bank = "ALPHA",
                            CalculationDaly = 0,
                            Code = "D-22-160",
                            Completed = 0,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2957),
                            DayCost = 5.0,
                            DaysUntilPayment = -51,
                            DelayInPayment = 3,
                            Description = "Test Description Project_0",
                            Drawing = "KL-0",
                            DurationDate = new DateTime(2024, 4, 7, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2957),
                            EstPaymentDate = new DateTime(2024, 4, 7, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2957),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2957),
                            ManHours = 0,
                            Name = "Project_0",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 8, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2957),
                            PaymentDetailes = "Payment Detailes For Project_0",
                            PendingPayments = 0.0,
                            PlanType = 1,
                            WorkingDays = 200
                        },
                        new
                        {
                            Id = "98860854fd7e41f68414910c2161eb494",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-161",
                            Completed = 10,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3146),
                            DayCost = 6.0,
                            DaysUntilPayment = -54,
                            DelayInPayment = 8,
                            Description = "Test Description Project_6",
                            Drawing = "KL-1",
                            DurationDate = new DateTime(2024, 4, 10, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3146),
                            EstPaymentDate = new DateTime(2024, 4, 9, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3146),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3146),
                            ManHours = 4,
                            Name = "Project_1",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 11, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3146),
                            PaymentDetailes = "Payment Detailes For Project_3",
                            PendingPayments = 1.0,
                            PlanType = 0,
                            WorkingDays = 203
                        },
                        new
                        {
                            Id = "d7a8dac9771649a69478180af68804698",
                            Bank = "ALPHA",
                            CalculationDaly = 2,
                            Code = "D-22-162",
                            Completed = 20,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3321),
                            DayCost = 7.0,
                            DaysUntilPayment = -57,
                            DelayInPayment = 13,
                            Description = "Test Description Project_4",
                            Drawing = "KL-2",
                            DurationDate = new DateTime(2024, 4, 13, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3321),
                            EstPaymentDate = new DateTime(2024, 4, 11, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3321),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3321),
                            ManHours = 8,
                            Name = "Project_2",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 14, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3321),
                            PaymentDetailes = "Payment Detailes For Project_12",
                            PendingPayments = 2.0,
                            PlanType = 1,
                            WorkingDays = 206
                        },
                        new
                        {
                            Id = "37963bd92712463f8f9dd98060670f2e18",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 3,
                            Code = "D-22-163",
                            Completed = 30,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3451),
                            DayCost = 8.0,
                            DaysUntilPayment = -60,
                            DelayInPayment = 18,
                            Description = "Test Description Project_15",
                            Drawing = "KL-3",
                            DurationDate = new DateTime(2024, 4, 16, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3451),
                            EstPaymentDate = new DateTime(2024, 4, 13, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3451),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3451),
                            ManHours = 12,
                            Name = "Project_3",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3451),
                            PaymentDetailes = "Payment Detailes For Project_18",
                            PendingPayments = 3.0,
                            PlanType = 0,
                            WorkingDays = 209
                        },
                        new
                        {
                            Id = "b407d0a5d297497392ddc24b0266a84512",
                            Bank = "ALPHA",
                            CalculationDaly = 4,
                            Code = "D-22-164",
                            Completed = 40,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3712),
                            DayCost = 9.0,
                            DaysUntilPayment = -63,
                            DelayInPayment = 23,
                            Description = "Test Description Project_20",
                            Drawing = "KL-4",
                            DurationDate = new DateTime(2024, 4, 19, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3712),
                            EstPaymentDate = new DateTime(2024, 4, 15, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3712),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3712),
                            ManHours = 16,
                            Name = "Project_4",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 20, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3712),
                            PaymentDetailes = "Payment Detailes For Project_4",
                            PendingPayments = 4.0,
                            PlanType = 1,
                            WorkingDays = 212
                        },
                        new
                        {
                            Id = "2f50bc95eefe4ef7a5010cb1bb7280985",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-165",
                            Completed = 50,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3841),
                            DayCost = 10.0,
                            DaysUntilPayment = -66,
                            DelayInPayment = 28,
                            Description = "Test Description Project_10",
                            Drawing = "KL-5",
                            DurationDate = new DateTime(2024, 4, 22, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3841),
                            EstPaymentDate = new DateTime(2024, 4, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3841),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3841),
                            ManHours = 20,
                            Name = "Project_5",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 23, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(3841),
                            PaymentDetailes = "Payment Detailes For Project_5",
                            PendingPayments = 5.0,
                            PlanType = 0,
                            WorkingDays = 215
                        },
                        new
                        {
                            Id = "092a7ad5c1af440d90e69a311afa6f9a36",
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-166",
                            Completed = 60,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4022),
                            DayCost = 11.0,
                            DaysUntilPayment = -69,
                            DelayInPayment = 33,
                            Description = "Test Description Project_24",
                            Drawing = "KL-6",
                            DurationDate = new DateTime(2024, 4, 25, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4022),
                            EstPaymentDate = new DateTime(2024, 4, 19, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4022),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4022),
                            ManHours = 24,
                            Name = "Project_6",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 26, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4022),
                            PaymentDetailes = "Payment Detailes For Project_30",
                            PendingPayments = 6.0,
                            PlanType = 1,
                            WorkingDays = 218
                        },
                        new
                        {
                            Id = "19a7ceeac3a64225b523f9fa4704020442",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-167",
                            Completed = 70,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4183),
                            DayCost = 12.0,
                            DaysUntilPayment = -72,
                            DelayInPayment = 38,
                            Description = "Test Description Project_7",
                            Drawing = "KL-7",
                            DurationDate = new DateTime(2024, 4, 28, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4183),
                            EstPaymentDate = new DateTime(2024, 4, 21, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4183),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4183),
                            ManHours = 28,
                            Name = "Project_7",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 29, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4183),
                            PaymentDetailes = "Payment Detailes For Project_35",
                            PendingPayments = 7.0,
                            PlanType = 0,
                            WorkingDays = 221
                        },
                        new
                        {
                            Id = "c179b725625c4bcfb9413bcd0488244e32",
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-168",
                            Completed = 80,
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4327),
                            DayCost = 13.0,
                            DaysUntilPayment = -75,
                            DelayInPayment = 43,
                            Description = "Test Description Project_40",
                            Drawing = "KL-8",
                            DurationDate = new DateTime(2024, 5, 1, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4327),
                            EstPaymentDate = new DateTime(2024, 4, 23, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4327),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4327),
                            ManHours = 32,
                            Name = "Project_8",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 5, 2, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(4327),
                            PaymentDetailes = "Payment Detailes For Project_24",
                            PendingPayments = 8.0,
                            PlanType = 1,
                            WorkingDays = 224
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "dcfe36a2916c4577af6c95666984dee31",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2706),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2707),
                            Name = "Draftsmen"
                        },
                        new
                        {
                            Id = "2cfbf82ecc1a4a0bbaa75f4e45c784af2",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2718),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2719),
                            Name = "Engineers"
                        },
                        new
                        {
                            Id = "70e97594d0464c59834f9566fcca13d53",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2728),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2729),
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = "4aaef5f6e2a047fcabc6becc58d152c94",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2739),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2740),
                            Name = "COO"
                        },
                        new
                        {
                            Id = "54266dfb487b410cbf9e67d442c0ed3f5",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2752),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2753),
                            Name = "CTO"
                        },
                        new
                        {
                            Id = "ca0a3812602d4e759f506f531f69130c6",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2763),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2764),
                            Name = "CEO"
                        },
                        new
                        {
                            Id = "86a8f995885c4208b3a6768b0a0370887",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2772),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2773),
                            Name = "Guest"
                        },
                        new
                        {
                            Id = "7eff7e238d5a462283fd03fb72a7a5fa8",
                            CreatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2782),
                            LastUpdatedDate = new DateTime(2024, 2, 17, 21, 4, 53, 433, DateTimeKind.Local).AddTicks(2783),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.ProjectEmployee", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.User", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithOne("Customer")
                        .HasForeignKey("EmpiriaBMS.Models.Models.User", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaBMS.Models.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithOne("Invoice")
                        .HasForeignKey("EmpiriaMS.Models.Models.Invoice", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Navigation("ProjectEmployees");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("ProjectEmployees");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
