// <auto-generated />
using System;
using EmpiriaBMS.EF.CLI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpiriaBMS.EF.CLI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240212141120_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpiriaMS.Models.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "142340",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5949),
                            Description = "Test Description Client 0",
                            Email = "alexpl_0@gmail.com",
                            FirstName = "Platanios_Customer_0",
                            LastName = "Alexandros_0",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5951),
                            Phone1 = "6949277780"
                        },
                        new
                        {
                            Id = "142341",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6032),
                            Description = "Test Description Client 1",
                            Email = "alexpl_1@gmail.com",
                            FirstName = "Platanios_Customer_1",
                            LastName = "Alexandros_1",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6034),
                            Phone1 = "6949277781"
                        },
                        new
                        {
                            Id = "142342",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6066),
                            Description = "Test Description Client 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Customer_2",
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6067),
                            Phone1 = "6949277782"
                        },
                        new
                        {
                            Id = "142343",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6100),
                            Description = "Test Description Client 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Customer_3",
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6101),
                            Phone1 = "6949277783"
                        },
                        new
                        {
                            Id = "142344",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6165),
                            Description = "Test Description Client 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Customer_4",
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6166),
                            Phone1 = "6949277784"
                        },
                        new
                        {
                            Id = "142345",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6204),
                            Description = "Test Description Client 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Customer_5",
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6205),
                            Phone1 = "6949277785"
                        },
                        new
                        {
                            Id = "142346",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6236),
                            Description = "Test Description Client 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Customer_6",
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6237),
                            Phone1 = "6949277786"
                        },
                        new
                        {
                            Id = "142347",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6266),
                            Description = "Test Description Client 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Customer_7",
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6267),
                            Phone1 = "6949277787"
                        },
                        new
                        {
                            Id = "142348",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6319),
                            Description = "Test Description Client 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Customer_8",
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6320),
                            Phone1 = "6949277788"
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "142342",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5986),
                            Description = "Test Description Employee 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Employee_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5987),
                            Phone1 = "6949277782"
                        },
                        new
                        {
                            Id = "142343",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6043),
                            Description = "Test Description Employee 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Employee_3",
                            Hours = 11.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6045),
                            Phone1 = "6949277783"
                        },
                        new
                        {
                            Id = "142344",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6075),
                            Description = "Test Description Employee 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Employee_4",
                            Hours = 202.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6077),
                            Phone1 = "6949277784"
                        },
                        new
                        {
                            Id = "142345",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6110),
                            Description = "Test Description Employee 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Employee_5",
                            Hours = 3003.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6111),
                            Phone1 = "6949277785"
                        },
                        new
                        {
                            Id = "142346",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6179),
                            Description = "Test Description Employee 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Employee_6",
                            Hours = 40004.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6180),
                            Phone1 = "6949277786"
                        },
                        new
                        {
                            Id = "142347",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6214),
                            Description = "Test Description Employee 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Employee_7",
                            Hours = 500005.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6215),
                            Phone1 = "6949277787"
                        },
                        new
                        {
                            Id = "142348",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6246),
                            Description = "Test Description Employee 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Employee_8",
                            Hours = 6000006.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6247),
                            Phone1 = "6949277788"
                        },
                        new
                        {
                            Id = "142349",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6275),
                            Description = "Test Description Employee 9",
                            Email = "alexpl_9@gmail.com",
                            FirstName = "Platanios_Employee_9",
                            Hours = 70000007.0,
                            LastName = "Alexandros_9",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6277),
                            Phone1 = "6949277789"
                        },
                        new
                        {
                            Id = "1423410",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6332),
                            Description = "Test Description Employee 10",
                            Email = "alexpl_10@gmail.com",
                            FirstName = "Platanios_Employee_10",
                            Hours = 800000008.0,
                            LastName = "Alexandros_10",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6333),
                            Phone1 = "69492777810"
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fee")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = "142342",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6014),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 3001.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6015),
                            Mark = "Signature 142342",
                            Number = 76040,
                            Total = 0.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "142343",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6055),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 3010.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6056),
                            Mark = "Signature 142343",
                            Number = 45166,
                            Total = 1.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "142344",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6089),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 3100.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6090),
                            Mark = "Signature 142344",
                            Number = 49875,
                            Total = 2.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "142345",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6154),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 4000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6155),
                            Mark = "Signature 142345",
                            Number = 31259,
                            Total = 3.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "142346",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6193),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 13000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6194),
                            Mark = "Signature 142346",
                            Number = 55311,
                            Total = 4.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "142347",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6226),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 103000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6227),
                            Mark = "Signature 142347",
                            Number = 89217,
                            Total = 5.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "142348",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6256),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 1003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6257),
                            Mark = "Signature 142348",
                            Number = 67400,
                            Total = 6.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "142349",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6286),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 10003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6288),
                            Mark = "Signature 142349",
                            Number = 48507,
                            Total = 7.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "1423410",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6347),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 100003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6348),
                            Mark = "Signature 1423410",
                            Number = 36614,
                            Total = 8.0,
                            Vat = 24.0
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalculationDaly")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Completed")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("DayCost")
                        .HasColumnType("float");

                    b.Property<int?>("DaysUntilPayment")
                        .HasColumnType("int");

                    b.Property<int?>("DelayInPayment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drawing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DurationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaidFee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDetailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PendingPayments")
                        .HasColumnType("float");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "25460",
                            Bank = "ALPHA",
                            CalculationDaly = 0,
                            Code = "D-22-160",
                            Completed = 0,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6359),
                            CustomerId = "142347",
                            DayCost = 5.0,
                            DaysUntilPayment = -51,
                            DelayInPayment = 3,
                            Description = "Test Description Project_0",
                            Drawing = "KL-0",
                            DurationDate = new DateTime(2024, 4, 2, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6359),
                            EstPaymentDate = new DateTime(2024, 4, 2, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6359),
                            InvoiceId = "142348",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6359),
                            ManHours = 0,
                            Name = "Project_0",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 3, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6359),
                            PaymentDetailes = "Payment Detailes For Project_0",
                            PendingPayments = 0.0,
                            PlanType = 1,
                            WorkingDays = 200
                        },
                        new
                        {
                            Id = "25461",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-161",
                            Completed = 10,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6406),
                            CustomerId = "142343",
                            DayCost = 6.0,
                            DaysUntilPayment = -54,
                            DelayInPayment = 8,
                            Description = "Test Description Project_1",
                            Drawing = "KL-1",
                            DurationDate = new DateTime(2024, 4, 5, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6406),
                            EstPaymentDate = new DateTime(2024, 4, 4, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6406),
                            InvoiceId = "142344",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6406),
                            ManHours = 8,
                            Name = "Project_1",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 6, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6406),
                            PaymentDetailes = "Payment Detailes For Project_1",
                            PendingPayments = 1.0,
                            PlanType = 0,
                            WorkingDays = 203
                        },
                        new
                        {
                            Id = "25462",
                            Bank = "ALPHA",
                            CalculationDaly = 2,
                            Code = "D-22-162",
                            Completed = 20,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6430),
                            CustomerId = "142341",
                            DayCost = 7.0,
                            DaysUntilPayment = -57,
                            DelayInPayment = 13,
                            Description = "Test Description Project_2",
                            Drawing = "KL-2",
                            DurationDate = new DateTime(2024, 4, 8, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6430),
                            EstPaymentDate = new DateTime(2024, 4, 6, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6430),
                            InvoiceId = "142344",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6430),
                            ManHours = 32,
                            Name = "Project_2",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 9, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6430),
                            PaymentDetailes = "Payment Detailes For Project_2",
                            PendingPayments = 2.0,
                            PlanType = 1,
                            WorkingDays = 206
                        },
                        new
                        {
                            Id = "25463",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 3,
                            Code = "D-22-163",
                            Completed = 30,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6447),
                            CustomerId = "142347",
                            DayCost = 8.0,
                            DaysUntilPayment = -60,
                            DelayInPayment = 18,
                            Description = "Test Description Project_3",
                            Drawing = "KL-3",
                            DurationDate = new DateTime(2024, 4, 11, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6447),
                            EstPaymentDate = new DateTime(2024, 4, 8, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6447),
                            InvoiceId = "142345",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6447),
                            ManHours = 72,
                            Name = "Project_3",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6447),
                            PaymentDetailes = "Payment Detailes For Project_3",
                            PendingPayments = 3.0,
                            PlanType = 0,
                            WorkingDays = 209
                        },
                        new
                        {
                            Id = "25464",
                            Bank = "ALPHA",
                            CalculationDaly = 4,
                            Code = "D-22-164",
                            Completed = 40,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6464),
                            CustomerId = "142341",
                            DayCost = 9.0,
                            DaysUntilPayment = -63,
                            DelayInPayment = 23,
                            Description = "Test Description Project_4",
                            Drawing = "KL-4",
                            DurationDate = new DateTime(2024, 4, 14, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6464),
                            EstPaymentDate = new DateTime(2024, 4, 10, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6464),
                            InvoiceId = "142347",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6464),
                            ManHours = 128,
                            Name = "Project_4",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 15, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6464),
                            PaymentDetailes = "Payment Detailes For Project_4",
                            PendingPayments = 4.0,
                            PlanType = 1,
                            WorkingDays = 212
                        },
                        new
                        {
                            Id = "25465",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-165",
                            Completed = 50,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6479),
                            CustomerId = "142343",
                            DayCost = 10.0,
                            DaysUntilPayment = -66,
                            DelayInPayment = 28,
                            Description = "Test Description Project_5",
                            Drawing = "KL-5",
                            DurationDate = new DateTime(2024, 4, 17, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6479),
                            EstPaymentDate = new DateTime(2024, 4, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6479),
                            InvoiceId = "142346",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6479),
                            ManHours = 200,
                            Name = "Project_5",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 18, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6479),
                            PaymentDetailes = "Payment Detailes For Project_5",
                            PendingPayments = 5.0,
                            PlanType = 0,
                            WorkingDays = 215
                        },
                        new
                        {
                            Id = "25466",
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-166",
                            Completed = 60,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6492),
                            CustomerId = "142343",
                            DayCost = 11.0,
                            DaysUntilPayment = -69,
                            DelayInPayment = 33,
                            Description = "Test Description Project_6",
                            Drawing = "KL-6",
                            DurationDate = new DateTime(2024, 4, 20, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6492),
                            EstPaymentDate = new DateTime(2024, 4, 14, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6492),
                            InvoiceId = "142347",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6492),
                            ManHours = 288,
                            Name = "Project_6",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 21, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6492),
                            PaymentDetailes = "Payment Detailes For Project_6",
                            PendingPayments = 6.0,
                            PlanType = 1,
                            WorkingDays = 218
                        },
                        new
                        {
                            Id = "25467",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-167",
                            Completed = 70,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6531),
                            CustomerId = "142345",
                            DayCost = 12.0,
                            DaysUntilPayment = -72,
                            DelayInPayment = 38,
                            Description = "Test Description Project_7",
                            Drawing = "KL-7",
                            DurationDate = new DateTime(2024, 4, 23, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6531),
                            EstPaymentDate = new DateTime(2024, 4, 16, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6531),
                            InvoiceId = "142349",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6531),
                            ManHours = 392,
                            Name = "Project_7",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 24, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6531),
                            PaymentDetailes = "Payment Detailes For Project_7",
                            PendingPayments = 7.0,
                            PlanType = 0,
                            WorkingDays = 221
                        },
                        new
                        {
                            Id = "25468",
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-168",
                            Completed = 80,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6545),
                            CustomerId = "142345",
                            DayCost = 13.0,
                            DaysUntilPayment = -75,
                            DelayInPayment = 43,
                            Description = "Test Description Project_8",
                            Drawing = "KL-8",
                            DurationDate = new DateTime(2024, 4, 26, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6545),
                            EstPaymentDate = new DateTime(2024, 4, 18, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6545),
                            InvoiceId = "142347",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6545),
                            ManHours = 512,
                            Name = "Project_8",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 27, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6545),
                            PaymentDetailes = "Payment Detailes For Project_8",
                            PendingPayments = 8.0,
                            PlanType = 1,
                            WorkingDays = 224
                        },
                        new
                        {
                            Id = "25469",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-169",
                            Completed = 90,
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6559),
                            CustomerId = "142341",
                            DayCost = 14.0,
                            DaysUntilPayment = -78,
                            DelayInPayment = 48,
                            Description = "Test Description Project_9",
                            Drawing = "KL-9",
                            DurationDate = new DateTime(2024, 4, 29, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6559),
                            EstPaymentDate = new DateTime(2024, 4, 20, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6559),
                            InvoiceId = "142348",
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6559),
                            ManHours = 648,
                            Name = "Project_9",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 30, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(6559),
                            PaymentDetailes = "Payment Detailes For Project_9",
                            PendingPayments = 9.0,
                            PlanType = 0,
                            WorkingDays = 227
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5768),
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5810),
                            Name = "Draftsmen"
                        },
                        new
                        {
                            Id = "2",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5815),
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5817),
                            Name = "Engineers"
                        },
                        new
                        {
                            Id = "3",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5819),
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5820),
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = "4",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5822),
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5823),
                            Name = "COO"
                        },
                        new
                        {
                            Id = "5",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5825),
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5826),
                            Name = "CTO"
                        },
                        new
                        {
                            Id = "6",
                            CreatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5827),
                            LastUpdatedDate = new DateTime(2024, 2, 12, 16, 11, 20, 68, DateTimeKind.Local).AddTicks(5828),
                            Name = "CEO"
                        });
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.Property<string>("EmployeesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeesId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("EmployeeProject");
                });

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.Property<string>("EmployeesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RolesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeesId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("EmployeeRole");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaMS.Models.Models.Invoice", "Invoice")
                        .WithOne("Project")
                        .HasForeignKey("EmpiriaMS.Models.Models.Project", "InvoiceId");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaMS.Models.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaMS.Models.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
