// <auto-generated />
using System;
using EmpiriaBMS.EF.CLI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpiriaBMS.EF.CLI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240216141532_DisableSomeLogik")]
    partial class DisableSomeLogik
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpiriaBMS.Models.Models.ProjectEmployee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectEmployee");

                    b.HasData(
                        new
                        {
                            Id = "9310f3e26fa84881b34e52a2359160282",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9816),
                            EmployeeId = "b180dee3c7fa4d798730e7a49dfc192c6",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9818),
                            ProjectId = "25f03947ca1642638fe21c0ac672f20a4"
                        },
                        new
                        {
                            Id = "098538174bba408398bf748795c0a6c818",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6305),
                            EmployeeId = "a52e403472ae4d7097e9b4e9d19ad94b6",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6307),
                            ProjectId = "8e6d8a06a6c74e9f86da4cb3b480d83b18"
                        },
                        new
                        {
                            Id = "ed1833c8bea34a5a81fe7b0146e9f61330",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6718),
                            EmployeeId = "5d41925d76ee4b26a1d9c0038a208f9830",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6721),
                            ProjectId = "d3625be49a4b45838c90eb52f163610520"
                        },
                        new
                        {
                            Id = "7789d8fd6fd54d2092e0f04294dfe49a35",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7257),
                            EmployeeId = "5fe90d67d062443b8da1dc01b1b769bb7",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7258),
                            ProjectId = "bdd732004bd147838166eb96b9ac4da614"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "6954ce88536a4099bfa948c908e94cf00",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1579),
                            Description = "Test Description Client 0",
                            Email = "alexpl_0@gmail.com",
                            FirstName = "Platanios_Customer_0",
                            Hours = 0.0,
                            LastName = "Alexandros_0",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1580),
                            MidName = "",
                            Phone1 = "6949277780",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "cfef668022ed4bc8a874cc0992fe83ab0",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9129),
                            Description = "Test Description Employee 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Employee_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9130),
                            MidName = "",
                            Phone1 = "6949277782",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "4265411c156049a0af887992143f215f2",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9371),
                            Description = "Test Description Client 1",
                            Email = "alexpl_1@gmail.com",
                            FirstName = "Platanios_Customer_1",
                            Hours = 0.0,
                            LastName = "Alexandros_1",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9373),
                            MidName = "",
                            Phone1 = "6949277781",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "b180dee3c7fa4d798730e7a49dfc192c6",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9417),
                            Description = "Test Description Employee 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Employee_3",
                            Hours = 8.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9418),
                            MidName = "",
                            Phone1 = "6949277783",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "846f59b1a8664de5bcbdc98bfab24b2f10",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5825),
                            Description = "Test Description Client 2",
                            Email = "alexpl_2@gmail.com",
                            FirstName = "Platanios_Customer_2",
                            Hours = 0.0,
                            LastName = "Alexandros_2",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5827),
                            MidName = "",
                            Phone1 = "6949277782",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "77fdc61739bc40a796ca6d5c5d5118fc4",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5969),
                            Description = "Test Description Employee 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Employee_4",
                            Hours = 16.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5971),
                            MidName = "",
                            Phone1 = "6949277784",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "e0777d0b7a84470298806745537ee6a83",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6155),
                            Description = "Test Description Client 3",
                            Email = "alexpl_3@gmail.com",
                            FirstName = "Platanios_Customer_3",
                            Hours = 0.0,
                            LastName = "Alexandros_3",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6156),
                            MidName = "",
                            Phone1 = "6949277783",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "a52e403472ae4d7097e9b4e9d19ad94b6",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6200),
                            Description = "Test Description Employee 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Employee_5",
                            Hours = 24.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6202),
                            MidName = "",
                            Phone1 = "6949277785",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "250e21d5b7514e99badd0b75efd52e4f4",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6331),
                            Description = "Test Description Client 4",
                            Email = "alexpl_4@gmail.com",
                            FirstName = "Platanios_Customer_4",
                            Hours = 0.0,
                            LastName = "Alexandros_4",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6333),
                            MidName = "",
                            Phone1 = "6949277784",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "6f774794eea440c7acd5f76095736b2224",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6383),
                            Description = "Test Description Employee 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Employee_6",
                            Hours = 32.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6385),
                            MidName = "",
                            Phone1 = "6949277786",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "8290a668526045afb2035f9c265c9fab5",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6523),
                            Description = "Test Description Client 5",
                            Email = "alexpl_5@gmail.com",
                            FirstName = "Platanios_Customer_5",
                            Hours = 0.0,
                            LastName = "Alexandros_5",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6524),
                            MidName = "",
                            Phone1 = "6949277785",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "5d41925d76ee4b26a1d9c0038a208f9830",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6569),
                            Description = "Test Description Employee 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Employee_7",
                            Hours = 40.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6570),
                            MidName = "",
                            Phone1 = "6949277787",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "db8ff30ad9664722b0ff2c11b9dfe77030",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6759),
                            Description = "Test Description Client 6",
                            Email = "alexpl_6@gmail.com",
                            FirstName = "Platanios_Customer_6",
                            Hours = 0.0,
                            LastName = "Alexandros_6",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6761),
                            MidName = "",
                            Phone1 = "6949277786",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "0bcfa7ce9eec4a669a8f63d6e42752126",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6896),
                            Description = "Test Description Employee 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Employee_8",
                            Hours = 48.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6899),
                            MidName = "",
                            Phone1 = "6949277788",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "469f1aca44a74c8cb084fb9f3dbd9e127",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7078),
                            Description = "Test Description Client 7",
                            Email = "alexpl_7@gmail.com",
                            FirstName = "Platanios_Customer_7",
                            Hours = 0.0,
                            LastName = "Alexandros_7",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7080),
                            MidName = "",
                            Phone1 = "6949277787",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "5fe90d67d062443b8da1dc01b1b769bb7",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7126),
                            Description = "Test Description Employee 9",
                            Email = "alexpl_9@gmail.com",
                            FirstName = "Platanios_Employee_9",
                            Hours = 56.0,
                            LastName = "Alexandros_9",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7128),
                            MidName = "",
                            Phone1 = "6949277789",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "ea19ea732058451b99328ae26169d4fa48",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7279),
                            Description = "Test Description Client 8",
                            Email = "alexpl_8@gmail.com",
                            FirstName = "Platanios_Customer_8",
                            Hours = 0.0,
                            LastName = "Alexandros_8",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7281),
                            MidName = "",
                            Phone1 = "6949277788",
                            Phone2 = "",
                            Phone3 = ""
                        },
                        new
                        {
                            Id = "0b758c30b39b428f84deb20303103e5b48",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7329),
                            Description = "Test Description Employee 10",
                            Email = "alexpl_10@gmail.com",
                            FirstName = "Platanios_Employee_10",
                            Hours = 64.0,
                            LastName = "Alexandros_10",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7331),
                            MidName = "",
                            Phone1 = "69492777810",
                            Phone2 = "",
                            Phone3 = ""
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = "3660633bd7db4b9b87e4223aa8dda726",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1657),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1659),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "6954ce88536a4099bfa948c908e94cf00"
                        },
                        new
                        {
                            Id = "b88eddd761a24b959955b6f8949775e9",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9236),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9238),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "cfef668022ed4bc8a874cc0992fe83ab0"
                        },
                        new
                        {
                            Id = "1e9a0590f0d0468285e429d12d232d10",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9395),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9397),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "4265411c156049a0af887992143f215f2"
                        },
                        new
                        {
                            Id = "5a1785acdc124b74a68d90c50a16236e",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9740),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9742),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "b180dee3c7fa4d798730e7a49dfc192c6"
                        },
                        new
                        {
                            Id = "aff445667d264457842562d3d3799bf1",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5928),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5929),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "846f59b1a8664de5bcbdc98bfab24b2f10"
                        },
                        new
                        {
                            Id = "455abc2607204eb9947d4a63d5315379",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5997),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(5999),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "77fdc61739bc40a796ca6d5c5d5118fc4"
                        },
                        new
                        {
                            Id = "aba2c272fcfd4f6781644309ddca0604",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6179),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6180),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "e0777d0b7a84470298806745537ee6a83"
                        },
                        new
                        {
                            Id = "bd4aeb9d1e624258a0246ab360620fcc",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6223),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6225),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "a52e403472ae4d7097e9b4e9d19ad94b6"
                        },
                        new
                        {
                            Id = "888f3db2e8ef4d098923a16f254d90fe",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6359),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6361),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "250e21d5b7514e99badd0b75efd52e4f4"
                        },
                        new
                        {
                            Id = "ddefa22fa8c040bd85ad6107fb154939",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6434),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6436),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "6f774794eea440c7acd5f76095736b2224"
                        },
                        new
                        {
                            Id = "602add4077d54c44933ba3929959bbcf",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6547),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6549),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "8290a668526045afb2035f9c265c9fab5"
                        },
                        new
                        {
                            Id = "f350625118d04d339451b5c27e8fa0d0",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6594),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6596),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "5d41925d76ee4b26a1d9c0038a208f9830"
                        },
                        new
                        {
                            Id = "f02ea41ec36247768e9d2b90cd8cf204",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6860),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6862),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "db8ff30ad9664722b0ff2c11b9dfe77030"
                        },
                        new
                        {
                            Id = "f243abe2fc77400d88c918e59a94be46",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6940),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6942),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "0bcfa7ce9eec4a669a8f63d6e42752126"
                        },
                        new
                        {
                            Id = "d451dd6990e74043b4fccc0f5d0e0472",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7103),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7104),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "469f1aca44a74c8cb084fb9f3dbd9e127"
                        },
                        new
                        {
                            Id = "5169b912f6634693af583c0c5649ed44",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7149),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7150),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "5fe90d67d062443b8da1dc01b1b769bb7"
                        },
                        new
                        {
                            Id = "134606fb661d450e9a3ed03982cc566c",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7307),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7309),
                            RoleId = "ae5a22419c3d486cb713f22e9685320d8",
                            UserId = "ea19ea732058451b99328ae26169d4fa48"
                        },
                        new
                        {
                            Id = "d03f37ce2a614d1da542afb7fd041dd4",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7357),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7358),
                            RoleId = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            UserId = "0b758c30b39b428f84deb20303103e5b48"
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fee")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = "cd381961d4414dd689ed26064f6174320",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9282),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9285),
                            Fee = 3001.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9284),
                            Mark = "Signature 142340",
                            Number = 62656,
                            Total = 0.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "86c24b4a2db6406f9f49cb3b70fc458f5",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9762),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9765),
                            Fee = 3010.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9763),
                            Mark = "Signature 142346",
                            Number = 41950,
                            Total = 1.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "246095b27d024b4aaa1437f6f2373c896",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6025),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6028),
                            Fee = 3100.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6027),
                            Mark = "Signature 142348",
                            Number = 32590,
                            Total = 2.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "39ccbb514a3949b08b48b74ae5b27b019",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6248),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6251),
                            Fee = 4000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6250),
                            Mark = "Signature 1423412",
                            Number = 13463,
                            Total = 3.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "d978af407a6e4a7d8775d109c2b36efe24",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6460),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6463),
                            Fee = 13000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6462),
                            Mark = "Signature 1423416",
                            Number = 44948,
                            Total = 4.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "f02773df93b04b5f9fdbb7d48e5325ce15",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6631),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6634),
                            Fee = 103000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6632),
                            Mark = "Signature 1423430",
                            Number = 48350,
                            Total = 5.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "a0f4571106f54ebbb80306d028f1dfbe24",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7019),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7021),
                            Fee = 1003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7020),
                            Mark = "Signature 1423412",
                            Number = 87747,
                            Total = 6.0,
                            Vat = 24.0
                        },
                        new
                        {
                            Id = "adbb386e991145738107440f198a33497",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7171),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7174),
                            Fee = 10003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7173),
                            Mark = "Signature 1423414",
                            Number = 60263,
                            Total = 7.0,
                            Vat = 17.0
                        },
                        new
                        {
                            Id = "16af4f820c8641ea9d8b0db63dc735988",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7380),
                            Date = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7382),
                            Fee = 100003000.0,
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7381),
                            Mark = "Signature 1423432",
                            Number = 40145,
                            Total = 8.0,
                            Vat = 24.0
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalculationDaly")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Completed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("DayCost")
                        .HasColumnType("float");

                    b.Property<int?>("DaysUntilPayment")
                        .HasColumnType("int");

                    b.Property<int?>("DelayInPayment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drawing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DurationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaidFee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDetailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PendingPayments")
                        .HasColumnType("float");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "f008454064df440ca661fe07d268b9cc0",
                            Bank = "ALPHA",
                            CalculationDaly = 0,
                            Code = "D-22-160",
                            Completed = 0,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9314),
                            CustomerId = "6954ce88536a4099bfa948c908e94cf00",
                            DayCost = 5.0,
                            DaysUntilPayment = -51,
                            DelayInPayment = 3,
                            Description = "Test Description Project_0",
                            Drawing = "KL-0",
                            DurationDate = new DateTime(2024, 4, 6, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9314),
                            EstPaymentDate = new DateTime(2024, 4, 6, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9314),
                            InvoiceId = "cd381961d4414dd689ed26064f6174320",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9314),
                            ManHours = 0,
                            Name = "Project_0",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 7, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9314),
                            PaymentDetailes = "Payment Detailes For Project_0",
                            PendingPayments = 0.0,
                            PlanType = 1,
                            WorkingDays = 200
                        },
                        new
                        {
                            Id = "25f03947ca1642638fe21c0ac672f20a4",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-161",
                            Completed = 10,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9776),
                            DayCost = 6.0,
                            DaysUntilPayment = -54,
                            DelayInPayment = 8,
                            Description = "Test Description Project_4",
                            Drawing = "KL-1",
                            DurationDate = new DateTime(2024, 4, 9, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9776),
                            EstPaymentDate = new DateTime(2024, 4, 8, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9776),
                            InvoiceId = "86c24b4a2db6406f9f49cb3b70fc458f5",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9776),
                            ManHours = 4,
                            Name = "Project_1",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 10, 16, 15, 31, 600, DateTimeKind.Local).AddTicks(9776),
                            PaymentDetailes = "Payment Detailes For Project_6",
                            PendingPayments = 1.0,
                            PlanType = 0,
                            WorkingDays = 203
                        },
                        new
                        {
                            Id = "71d650d6dbeb424ea9a62de38dfe8ebe8",
                            Bank = "ALPHA",
                            CalculationDaly = 2,
                            Code = "D-22-162",
                            Completed = 20,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6058),
                            CustomerId = "846f59b1a8664de5bcbdc98bfab24b2f10",
                            DayCost = 7.0,
                            DaysUntilPayment = -57,
                            DelayInPayment = 13,
                            Description = "Test Description Project_2",
                            Drawing = "KL-2",
                            DurationDate = new DateTime(2024, 4, 12, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6058),
                            EstPaymentDate = new DateTime(2024, 4, 10, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6058),
                            InvoiceId = "246095b27d024b4aaa1437f6f2373c896",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6058),
                            ManHours = 8,
                            Name = "Project_2",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 13, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6058),
                            PaymentDetailes = "Payment Detailes For Project_8",
                            PendingPayments = 2.0,
                            PlanType = 1,
                            WorkingDays = 206
                        },
                        new
                        {
                            Id = "8e6d8a06a6c74e9f86da4cb3b480d83b18",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 3,
                            Code = "D-22-163",
                            Completed = 30,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6265),
                            DayCost = 8.0,
                            DaysUntilPayment = -60,
                            DelayInPayment = 18,
                            Description = "Test Description Project_18",
                            Drawing = "KL-3",
                            DurationDate = new DateTime(2024, 4, 15, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6265),
                            EstPaymentDate = new DateTime(2024, 4, 12, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6265),
                            InvoiceId = "39ccbb514a3949b08b48b74ae5b27b019",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6265),
                            ManHours = 12,
                            Name = "Project_3",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6265),
                            PaymentDetailes = "Payment Detailes For Project_9",
                            PendingPayments = 3.0,
                            PlanType = 0,
                            WorkingDays = 209
                        },
                        new
                        {
                            Id = "95ac63b1756a4da59c0796f6cb5337c924",
                            Bank = "ALPHA",
                            CalculationDaly = 4,
                            Code = "D-22-164",
                            Completed = 40,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6479),
                            CustomerId = "250e21d5b7514e99badd0b75efd52e4f4",
                            DayCost = 9.0,
                            DaysUntilPayment = -63,
                            DelayInPayment = 23,
                            Description = "Test Description Project_24",
                            Drawing = "KL-4",
                            DurationDate = new DateTime(2024, 4, 18, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6479),
                            EstPaymentDate = new DateTime(2024, 4, 14, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6479),
                            InvoiceId = "d978af407a6e4a7d8775d109c2b36efe24",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6479),
                            ManHours = 16,
                            Name = "Project_4",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 19, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6479),
                            PaymentDetailes = "Payment Detailes For Project_12",
                            PendingPayments = 4.0,
                            PlanType = 1,
                            WorkingDays = 212
                        },
                        new
                        {
                            Id = "d3625be49a4b45838c90eb52f163610520",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-165",
                            Completed = 50,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6657),
                            DayCost = 10.0,
                            DaysUntilPayment = -66,
                            DelayInPayment = 28,
                            Description = "Test Description Project_5",
                            Drawing = "KL-5",
                            DurationDate = new DateTime(2024, 4, 21, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6657),
                            EstPaymentDate = new DateTime(2024, 4, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6657),
                            InvoiceId = "f02773df93b04b5f9fdbb7d48e5325ce15",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6657),
                            ManHours = 20,
                            Name = "Project_5",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 22, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(6657),
                            PaymentDetailes = "Payment Detailes For Project_25",
                            PendingPayments = 5.0,
                            PlanType = 0,
                            WorkingDays = 215
                        },
                        new
                        {
                            Id = "b4a01ee468214a9ba7f279ea48188c6924",
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-166",
                            Completed = 60,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7037),
                            CustomerId = "db8ff30ad9664722b0ff2c11b9dfe77030",
                            DayCost = 11.0,
                            DaysUntilPayment = -69,
                            DelayInPayment = 33,
                            Description = "Test Description Project_24",
                            Drawing = "KL-6",
                            DurationDate = new DateTime(2024, 4, 24, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7037),
                            EstPaymentDate = new DateTime(2024, 4, 18, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7037),
                            InvoiceId = "a0f4571106f54ebbb80306d028f1dfbe24",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7037),
                            ManHours = 24,
                            Name = "Project_6",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 25, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7037),
                            PaymentDetailes = "Payment Detailes For Project_12",
                            PendingPayments = 6.0,
                            PlanType = 1,
                            WorkingDays = 218
                        },
                        new
                        {
                            Id = "bdd732004bd147838166eb96b9ac4da614",
                            Bank = "NBG_IBANK",
                            CalculationDaly = 1,
                            Code = "D-22-167",
                            Completed = 70,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7187),
                            DayCost = 12.0,
                            DaysUntilPayment = -72,
                            DelayInPayment = 38,
                            Description = "Test Description Project_7",
                            Drawing = "KL-7",
                            DurationDate = new DateTime(2024, 4, 27, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7187),
                            EstPaymentDate = new DateTime(2024, 4, 20, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7187),
                            InvoiceId = "adbb386e991145738107440f198a33497",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7187),
                            ManHours = 28,
                            Name = "Project_7",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 4, 28, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7187),
                            PaymentDetailes = "Payment Detailes For Project_7",
                            PendingPayments = 7.0,
                            PlanType = 0,
                            WorkingDays = 221
                        },
                        new
                        {
                            Id = "d46ec5d3b5c84f759b0660c14f48125024",
                            Bank = "ALPHA",
                            CalculationDaly = 1,
                            Code = "D-22-168",
                            Completed = 80,
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7396),
                            CustomerId = "ea19ea732058451b99328ae26169d4fa48",
                            DayCost = 13.0,
                            DaysUntilPayment = -75,
                            DelayInPayment = 43,
                            Description = "Test Description Project_40",
                            Drawing = "KL-8",
                            DurationDate = new DateTime(2024, 4, 30, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7396),
                            EstPaymentDate = new DateTime(2024, 4, 22, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7396),
                            InvoiceId = "16af4f820c8641ea9d8b0db63dc735988",
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7396),
                            ManHours = 32,
                            Name = "Project_8",
                            PaidFee = 5.0,
                            PaymentDate = new DateTime(2024, 5, 1, 16, 15, 31, 602, DateTimeKind.Local).AddTicks(7396),
                            PaymentDetailes = "Payment Detailes For Project_40",
                            PendingPayments = 8.0,
                            PlanType = 1,
                            WorkingDays = 224
                        });
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "6ef759a8c2534fe1a7a74f82f6bb43b51",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1239),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1241),
                            Name = "Draftsmen"
                        },
                        new
                        {
                            Id = "7a45b1fd0b594822bc35411234807b072",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1258),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1260),
                            Name = "Engineers"
                        },
                        new
                        {
                            Id = "d69bd6b40d7343eca44dc6cf3b5095f63",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1274),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1276),
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = "aa667da11b514452b6e9942763da0d074",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1292),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1294),
                            Name = "COO"
                        },
                        new
                        {
                            Id = "8c1e3d5544cd4d26b759350d0df433425",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1311),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1314),
                            Name = "CTO"
                        },
                        new
                        {
                            Id = "8fedba7fdc124e2780ae994b302d9a966",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1330),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1332),
                            Name = "CEO"
                        },
                        new
                        {
                            Id = "eba98ffc9950444dbcde9283f74386597",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1350),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1353),
                            Name = "Guest"
                        },
                        new
                        {
                            Id = "ae5a22419c3d486cb713f22e9685320d8",
                            CreatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1368),
                            LastUpdatedDate = new DateTime(2024, 2, 16, 16, 15, 31, 599, DateTimeKind.Local).AddTicks(1370),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.ProjectEmployee", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaMS.Models.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.UserRole", b =>
                {
                    b.HasOne("EmpiriaMS.Models.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpiriaBMS.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Project", b =>
                {
                    b.HasOne("EmpiriaBMS.Models.Models.User", "Customer")
                        .WithOne("Project")
                        .HasForeignKey("EmpiriaMS.Models.Models.Project", "CustomerId");

                    b.HasOne("EmpiriaMS.Models.Models.Invoice", "Invoice")
                        .WithOne("Project")
                        .HasForeignKey("EmpiriaMS.Models.Models.Project", "InvoiceId");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("EmpiriaBMS.Models.Models.User", b =>
                {
                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmpiriaMS.Models.Models.Invoice", b =>
                {
                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
