name: EmpiriaBMS-Front
on:
    push:
        tags:
            - '*-staging-no'
    workflow_dispatch: {}
env:
  AZURE_WEBAPP_NAME: EmpiriaBMS-Front
  AZURE_WEBAPP_PACKAGE_PATH: EmpiriaBMS.Front\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: EmpiriaBMS.Front
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Restore Logging/Logging.csproj
      run: dotnet restore "Logging/Logging.csproj"
    - name: Restore EmpiriaBMS.Models/EmpiriaBMS.Models.csproj
      run: dotnet restore "EmpiriaBMS.Models/EmpiriaBMS.Models.csproj"
    - name: Restore EmpiriaBMS.Core/EmpiriaBMS.Core.csproj
      run: dotnet restore "EmpiriaBMS.Core/EmpiriaBMS.Core.csproj"
    - name: Restore EmpiriaBMS.Front/EmpiriaBMS.Front.csproj
      run: dotnet restore "EmpiriaBMS.Front/EmpiriaBMS.Front.csproj"

    - name: Build
      run: dotnet build "EmpiriaBMS.Front/EmpiriaBMS.Front.csproj" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.EmpiriaBMS_Front_914E }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
